/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.umk.mat.ksiegarnia.view.services;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Mariusz
 */
public class CreateNewUserView extends ServicesView {

 
    public CreateNewUserView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameUser = new javax.swing.JTextField();
        surnameUser = new javax.swing.JTextField();
        addressUser = new javax.swing.JTextField();
        phoneUser = new javax.swing.JTextField();
        loginUser = new javax.swing.JTextField();
        cancelRegister = new javax.swing.JButton();
        registerUser = new javax.swing.JButton();
        passUser = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(415, 535));
        getContentPane().setLayout(null);
        getContentPane().add(nameUser);
        nameUser.setBounds(190, 250, 150, 29);
        getContentPane().add(surnameUser);
        surnameUser.setBounds(190, 300, 150, 29);
        getContentPane().add(addressUser);
        addressUser.setBounds(190, 350, 150, 29);
        getContentPane().add(phoneUser);
        phoneUser.setBounds(190, 400, 150, 29);
        getContentPane().add(loginUser);
        loginUser.setBounds(190, 150, 150, 29);

        cancelRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Anuluj.gif"))); // NOI18N
        cancelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelRegisterMouseExited(evt);
            }
        });
        getContentPane().add(cancelRegister);
        cancelRegister.setBounds(40, 450, 150, 30);

        registerUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Zarejestruj.gif"))); // NOI18N
        registerUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerUserMouseExited(evt);
            }
        });
        getContentPane().add(registerUser);
        registerUser.setBounds(240, 450, 140, 30);
        getContentPane().add(passUser);
        passUser.setBounds(190, 200, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/tło1.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 400, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRegisterMouseEntered
        cancelRegister.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/AnulujClick.gif")));
    }//GEN-LAST:event_cancelRegisterMouseEntered
 
    private void registerUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserMouseEntered
        registerUser.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/ZarejestrujClick.gif")));
    }//GEN-LAST:event_registerUserMouseEntered

    private void cancelRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRegisterMouseExited
        cancelRegister.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Anuluj.gif")));
    }//GEN-LAST:event_cancelRegisterMouseExited

    private void registerUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerUserMouseExited
        registerUser.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Zarejestruj.gif")));
    }//GEN-LAST:event_registerUserMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewUserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressUser;
    private javax.swing.JButton cancelRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginUser;
    private javax.swing.JTextField nameUser;
    private javax.swing.JPasswordField passUser;
    private javax.swing.JTextField phoneUser;
    private javax.swing.JButton registerUser;
    private javax.swing.JTextField surnameUser;
    // End of variables declaration//GEN-END:variables
    
    /**
     * 
     * @return user login from field in view
     */
    public String getLogin()
    {
    	return loginUser.getText();
    }
    /**
     * 
     * @return user password from field in view
     */
    public String getPassword()
    {
    	return passUser.getText();
    }
    /**
     * 
     * @return user name from field in view
     */
    public String getName()
    {
    	return nameUser.getText();
    }
    /**
     * 
     * @return user surname from field in view
     */
    public String getSurname()
    {
    	return surnameUser.getText();
    }
    /**
     * 
     * @return user address from field in view
     */
    public String getAddress()
    {
    	return addressUser.getText();
    }
    /**
     * 
     * @return user phone from field in view
     */
    public String getPhone()
    {
    	return phoneUser.getText();
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setRegisterUserActionListener(ActionListener listener)
    {
    	registerUser.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setCancelRegisterrActionListener(ActionListener listener)
    {
    	cancelRegister.addActionListener(listener);
    }
}
