/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.umk.mat.ksiegarnia.view.admin;

import java.awt.event.ActionListener;

import javax.swing.ImageIcon;

import pl.umk.mat.ksiegarnia.view.services.ServicesView;


/**
 *
 * @author Mariusz
 */
public class AdminMainMenuView extends ServicesView {

    /**
     * Creates new form AdminMainMenu
     */
    public AdminMainMenuView() {
        initComponents();
        boxFull.setVisible(false);boxEmpty.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThreadMessage = new javax.swing.JLabel();
        addBook = new javax.swing.JButton();
        deleteBook = new javax.swing.JButton();
        ordersToDo = new javax.swing.JButton();
        ordersDone = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        boxEmpty = new javax.swing.JLabel();
        boxFull = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(745, 425));
        getContentPane().setLayout(null);

        ThreadMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ThreadMessage.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ThreadMessage);
        ThreadMessage.setBounds(370, 110, 220, 30);

        addBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Dodaj Ksiazke.jpg"))); // NOI18N
        addBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBookMouseExited(evt);
            }
        });
        getContentPane().add(addBook);
        addBook.setBounds(50, 170, 200, 30);

        deleteBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Usun Ksiazke.jpg"))); // NOI18N
        deleteBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBookMouseExited(evt);
            }
        });
        getContentPane().add(deleteBook);
        deleteBook.setBounds(50, 230, 200, 30);

        ordersToDo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Zamowienia.jpg"))); // NOI18N
        ordersToDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersToDoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersToDoMouseExited(evt);
            }
        });
        getContentPane().add(ordersToDo);
        ordersToDo.setBounds(270, 170, 200, 90);

        ordersDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Zrealizowane zamowienia.jpg"))); // NOI18N
        ordersDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ordersDoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ordersDoneMouseExited(evt);
            }
        });
        getContentPane().add(ordersDone);
        ordersDone.setBounds(500, 170, 200, 90);

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Wyloguj.jpg"))); // NOI18N
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutMouseExited(evt);
            }
        });
        getContentPane().add(logOut);
        logOut.setBounds(630, 0, 100, 30);

        boxEmpty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/empty.png"))); // NOI18N
        getContentPane().add(boxEmpty);
        boxEmpty.setBounds(290, 80, 80, 70);

        boxFull.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/full.png"))); // NOI18N
        getContentPane().add(boxFull);
        boxFull.setBounds(290, 80, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/Admin menuTło.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookMouseEntered
        addBook.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Dodaj KsiazkeClick.jpg")));    
    }//GEN-LAST:event_addBookMouseEntered

    private void deleteBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookMouseEntered
        deleteBook.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Usun KsiazkeClick.jpg"))); 
    }//GEN-LAST:event_deleteBookMouseEntered

    private void ordersToDoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersToDoMouseEntered
        ordersToDo.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Zamowienia Click.jpg"))); 
    }//GEN-LAST:event_ordersToDoMouseEntered

    private void ordersDoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersDoneMouseEntered
        ordersDone.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Zrealizowane zamowienia Click.jpg"))); 
    }//GEN-LAST:event_ordersDoneMouseEntered

    private void logOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseEntered
        logOut.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/WylogujClick.jpg"))); 
    }//GEN-LAST:event_logOutMouseEntered

    private void addBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookMouseExited
        addBook.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Dodaj Ksiazke.jpg"))); 
    }//GEN-LAST:event_addBookMouseExited

    private void deleteBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBookMouseExited
        deleteBook.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Usun Ksiazke.jpg"))); 
    }//GEN-LAST:event_deleteBookMouseExited

    private void ordersToDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersToDoMouseExited
        ordersToDo.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Zamowienia.jpg"))); 
    }//GEN-LAST:event_ordersToDoMouseExited

    private void ordersDoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordersDoneMouseExited
        ordersDone.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Zrealizowane zamowienia.jpg")));
    }//GEN-LAST:event_ordersDoneMouseExited

    private void logOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseExited
        logOut.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/Wyloguj.jpg"))); 
    }//GEN-LAST:event_logOutMouseExited
   
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenuView().setVisible(true);            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel ThreadMessage;
    private javax.swing.JButton addBook;
    private static javax.swing.JLabel boxEmpty;
    private static javax.swing.JLabel boxFull;
    private javax.swing.JButton deleteBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logOut;
    private javax.swing.JButton ordersDone;
    private javax.swing.JButton ordersToDo;
    // End of variables declaration//GEN-END:variables
    
    /**
     * sets listener on button
     * @param listener
     */
    public void setAddBookActionListener(ActionListener listener)
    {
    	addBook.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setDeleteBookActionListener(ActionListener listener)
    {
    	deleteBook.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setLogOutActionListener(ActionListener listener)
    {
    	logOut.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setOrdersDoneActionListener(ActionListener listener)
    {
    	ordersDone.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setOrdersToDoActionListener(ActionListener listener)
    {
    	ordersToDo.addActionListener(listener);
    }
    /**
     * shows full box when true and empty box when false
     * @param Boolean
     */
    public void setNewOrderIcon(Boolean viewBox)
    {
    	if(viewBox)
    	{
    		boxEmpty.setVisible(false);    		
    		ThreadMessage.setText("Nowe zamowienie");
    		boxFull.setVisible(true);
    	}
    	else
    	{
    		boxFull.setVisible(false);
            ThreadMessage.setText("Brak zamowien");
            boxEmpty.setVisible(true);
    	}
    	
    }
    
}
