/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.umk.mat.ksiegarnia.view.client;

import java.awt.event.ActionListener;

import javax.swing.ImageIcon;

import pl.umk.mat.ksiegarnia.view.services.ServicesView;

/**
 *
 * @author Mariusz
 */
public class ConfirmOrderView extends ServicesView {

    /**
     * Creates new form MakeOrder
     */
    public ConfirmOrderView() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyBank = new javax.swing.JTextField();
        companyStreet = new javax.swing.JTextField();
        companyName = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        userAddress = new javax.swing.JTextField();
        userPhone = new javax.swing.JTextField();
        allCost = new javax.swing.JTextField();
        cancelTransaction = new javax.swing.JButton();
        submitOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(468, 520));
        getContentPane().setLayout(null);

        companyBank.setEditable(false);
        companyBank.setText("334564324564356432456643");
        getContentPane().add(companyBank);
        companyBank.setBounds(190, 130, 190, 30);

        companyStreet.setEditable(false);
        companyStreet.setText("ul. zmyslona 12, 00-000 Torn");
        getContentPane().add(companyStreet);
        companyStreet.setBounds(190, 90, 190, 30);

        companyName.setEditable(false);
        companyName.setText("Mariusz Różański, Wiedzopedia");
        getContentPane().add(companyName);
        companyName.setBounds(190, 50, 190, 30);

        userName.setEditable(false);
        getContentPane().add(userName);
        userName.setBounds(190, 200, 190, 30);

        userAddress.setEditable(false);
        getContentPane().add(userAddress);
        userAddress.setBounds(190, 240, 190, 30);

        userPhone.setEditable(false);
        getContentPane().add(userPhone);
        userPhone.setBounds(190, 280, 190, 30);

        allCost.setEditable(false);
        getContentPane().add(allCost);
        allCost.setBounds(210, 360, 100, 30);

        cancelTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskAnuluj.png"))); // NOI18N
        cancelTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelTransactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelTransactionMouseExited(evt);
            }
        });
        getContentPane().add(cancelTransaction);
        cancelTransaction.setBounds(40, 420, 150, 50);

        submitOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskPotwierdz.png"))); // NOI18N
        submitOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitOrderMouseExited(evt);
            }
        });
        getContentPane().add(submitOrder);
        submitOrder.setBounds(260, 420, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/DokonczTransakcje_tlo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTransactionMouseEntered
        cancelTransaction.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskAnulujClick.gif")));
    }//GEN-LAST:event_cancelTransactionMouseEntered

    private void submitOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitOrderMouseEntered
        submitOrder.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskPotwierdzClick.gif")));
    }//GEN-LAST:event_submitOrderMouseEntered

    private void cancelTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelTransactionMouseExited
        cancelTransaction.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskAnuluj.png"))); 
    }//GEN-LAST:event_cancelTransactionMouseExited

    private void submitOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitOrderMouseExited
        submitOrder.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskPotwierdz.png")));
    }//GEN-LAST:event_submitOrderMouseExited


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmOrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField allCost;
    private javax.swing.JButton cancelTransaction;
    private javax.swing.JTextField companyBank;
    private javax.swing.JTextField companyName;
    private javax.swing.JTextField companyStreet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitOrder;
    private javax.swing.JTextField userAddress;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userPhone;
    // End of variables declaration//GEN-END:variables
    
    /**
     * shows user information in view
     * @param name
     * @param surname
     * @param address
     * @param phone
     * @param cost
     */
    public void setUserInfoFields(String name, String surname, String address, String phone, String cost )
    {
    	userName.setText(name + " " + surname);
    	userAddress.setText(address);
    	userPhone.setText(phone);
    	allCost.setText(cost);  
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setSubmitOrderActionListener(ActionListener listener)
    {
    	submitOrder.addActionListener(listener);
    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setCancelTransactionActionListener(ActionListener listener)
    {
    	cancelTransaction.addActionListener(listener);
    }
}
