/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.umk.mat.ksiegarnia.view.client;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import pl.umk.mat.ksiegarnia.model.Client;
import pl.umk.mat.ksiegarnia.model.book.BookInformation;
import pl.umk.mat.ksiegarnia.view.services.ServicesView;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariusz
 */
public class OrdersView extends ServicesView {

    /**
     * Creates new form MyBasket
     */

    public OrdersView() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBasket = new javax.swing.JTable();
        mainMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(null);

        tableBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tytuł", "Autor", "Wydawnictwo", "Data Wydania", "Cena", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBasket);
        if (tableBasket.getColumnModel().getColumnCount() > 0) {
            tableBasket.getColumnModel().getColumn(0).setResizable(false);
            tableBasket.getColumnModel().getColumn(1).setResizable(false);
            tableBasket.getColumnModel().getColumn(2).setResizable(false);
            tableBasket.getColumnModel().getColumn(3).setResizable(false);
            tableBasket.getColumnModel().getColumn(4).setResizable(false);
            tableBasket.getColumnModel().getColumn(4).setPreferredWidth(10);
            tableBasket.getColumnModel().getColumn(5).setResizable(false);
            tableBasket.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 70, 800, 330);

        mainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskMenuGłówne.gif"))); // NOI18N
        mainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainMenuMouseExited(evt);
            }
        });
        getContentPane().add(mainMenu);
        mainMenu.setBounds(60, 410, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ksiegarnia/img/mojeZamowienia_tlo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseEntered
        mainMenu.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskMenuGłówneClick.gif")));
    }//GEN-LAST:event_mainMenuMouseEntered

    private void mainMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuMouseExited
        mainMenu.setIcon(new ImageIcon(getClass().getResource("/ksiegarnia/img/PrzyciskMenuGłówne.gif")));
    }//GEN-LAST:event_mainMenuMouseExited
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new OrdersView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mainMenu;
    private javax.swing.JTable tableBasket;
    // End of variables declaration//GEN-END:variables
    
    /**
     * shows all orders which client did
     * @param ArrayList<BookInformation>
     */
    public void showTable(ArrayList<BookInformation> allBooks) {
    	
        DefaultTableModel model = (DefaultTableModel) tableBasket.getModel();
        for (BookInformation curBook : allBooks) {
            String status;
            if(curBook.getSend()) status = "Wyslano"; 
            else status = "Trwa realizacja";
            model.addRow(new Object[]{curBook.getTitle(), curBook.getAuthor(), curBook.getPH(), curBook.getDate(), curBook.getPrice(),status });
        }

    }
    /**
     * sets listener on button
     * @param listener
     */
    public void setMainMenuActionListener(ActionListener listener)
    {
    	mainMenu.addActionListener(listener);
    }
}
